# Generated by Django 4.0.5 on 2022-07-06 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Medical',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('procedure_description', models.CharField(max_length=255)),
                ('medication', models.CharField(max_length=255)),
                ('done_at', models.DateTimeField(auto_now_add=True)),
                ('animal_Id', models.IntegerField()),
            ],
            options={
                'db_table': 'Medical_Histories',
            },
        ),
    ]
