import { StyleSheet, Dimensions } from "react-native";

const windowWidth = Dimensions.get("window").width;
const windowHeight = Dimensions.get("window").height;

const infoStyles = StyleSheet.create({
  infoCard: {
    width: 0.85 * windowWidth,
    height: 0.25 * windowHeight,
  },
  attr: {
    flex: 1,
    justifyContent: "center",
    flexDirection: "row",
    justifyContent: "space-between",
    width: 0.9 * windowWidth,
    margin: 20,
    paddingVertical: 20,
    paddingRight: 20,
    paddingLeft: 30,
  },
  list: {
    flex: 1,
    flexDirection: "column",
    justifyContent: "space-evenly",
  },
  circle: {
    width: 140,
    height: 150,
    backgroundColor: "#344E41",
    position: "absolute",
    right: 0,
    top: 0,
    borderRadius: 50,
  },
  circle2: {
    width: 350,
    height: 150,
    backgroundColor: "#fff",
    position: "absolute",
    borderWidth: 1,
    borderRadius: 50,
    left: 0,
    top: 0,
  },
  picture: {
    width: 100,
    height: 100,
    borderRadius: 8,
    backgroundColor: "red",
  },
  actionCard: {
    width: 200,
    height: 50,
    backgroundColor: "#DAD7CD",
    borderRadius: 8,
    alignItems: "center",
    justifyContent: "center",
    borderColor: "#2A432A",
    borderWidth: 1,
  },
  actionsContainer: {
    height: windowHeight * 0.15,
    width: windowWidth,
    flexDirection: "column",
    justifyContent: "space-between",
    alignItems: "center",
    paddingTop: 10,
    paddingHorizontal: 40,
    marginBottom: 50,
  },
  medicalCard: {
    color: "black",
    height: 0.35 * windowHeight,
    justifyContent: "center",
    flexDirection: "column",
    marginHorizontal: 0.1 * windowWidth,
  },
  card: {
    backgroundColor: "#DAD7CD",
    borderColor: "#2A432A",
    flexDirection: "row",
    justifyContent: "space-around",
    borderWidth: 1,
    width: 0.8 * windowWidth,
    alignItems: "center",
    marginVertical: 5,
    height: 50,
    borderRadius: 8,
  },
  createMedicalRecordButtonContainer: {
    width: windowWidth * 0.8,
    top: -0.4 * windowHeight,
    right: -0.1 * windowWidth,
    height: 25,
    justifyContent: "center",
    alignItems: "flex-start",
  },
  button: {
    width: 100,
    height: 60,
    backgroundColor: "#D46C4E",
    borderColor: "#2A432A",
    borderWidth: 1,
    alignItems: "center",
    justifyContent: "center",
    borderRadius: 8,
    paddingHorizontal: 20,
  },
  password: {
    borderBottomWidth: 1,
    width: 115,
  },
  backButton: {
    backgroundColor: "#ACC0B3",
    width: 80,
    height: 40,
    borderWidth: 1,
    borderRadius: 10,
    alignItems: "center",
    justifyContent: "center",
    margin: 20,
  },
  messageContainer: {
    width: windowWidth,
    justifyContent: "center",
    alignItems: "center",
  },
  message: { textAlign: "center", color: "white", fontWeight: "600" },
  success: {
    backgroundColor: "#ACC0B3",
    textAlignVertical: "center",
    width: 120,
    height: 30,
    borderRadius: 8,
  },
  error: {
    backgroundColor: "#B00020",
    textAlignVertical: "center",
    width: 120,
    height: 30,
    borderRadius: 8,
  },
  enlarge: {
    backgroundColor: "#DAD7CD",
    borderColor: "#2A432A",
    flexDirection: "column",
    justifyContent: "space-around",
    borderWidth: 1,
    width: 0.8 * windowWidth,
    alignItems: "center",
    marginVertical: 5,
    height: 80,
    borderRadius: 8,
  },
  slant: {
    position: "absolute",
    height: windowHeight * 1.2,
    backgroundColor: "#344E41",
    width: windowWidth * 2,
    top: 0,
    right: 0,
    transform: [{ rotateY: "120deg" }, { rotateX: "45deg" }],
  },
  profileCardContainer: {
    width: windowWidth,
    height: 0.25 * windowHeight,
  },
  profileCard: {
    flex: 1,
    justifyContent: "center",
    flexDirection: "row",
    justifyContent: "space-between",
    width: 0.5 * windowWidth,
    margin: 20,
    paddingVertical: 20,
    paddingRight: 20,
    paddingLeft: 30,
    backgroundColor: "#DAD7CD",
    borderRadius: 12,
    elevation: 10,
  },
});

export { infoStyles };
