import { StyleSheet, Dimensions } from "react-native";

const windowWidth = Dimensions.get("window").width;
const windowHeight = Dimensions.get("window").height;

const infoStyles = StyleSheet.create({
  infoCard: {
    width: windowWidth,
    height: 0.25 * windowHeight,
  },
  attr: {
    flex: 1,
    justifyContent: "center",
    flexDirection: "row",
    justifyContent: "space-between",
    width: 0.9 * windowWidth,
    borderWidth: 1,
    margin: 20,
    paddingVertical: 20,
    paddingTop: 5,
    paddingHorizontal: 20,
    borderRadius: 10,
    borderColor: "#91BCA0",
  },
  list: {
    flex: 1,
    flexDirection: "column",
    justifyContent: "space-evenly",
  },
  picture: {
    width: 100,
    height: 100,
    borderRadius: 8,
    backgroundColor: "red",
  },
  actionCard: {
    width: 200,
    height: 50,
    backgroundColor: "#DAD7CD",
    borderRadius: 8,
    alignItems: "center",
    justifyContent: "center",
    borderColor: "#2A432A",
    borderWidth: 1,
  },
  actionsContainer: {
    height: windowHeight * 0.15,
    width: windowWidth,
    flexDirection: "column",
    justifyContent: "space-between",
    alignItems: "center",
    paddingTop: 10,
    paddingHorizontal: 40,
    marginBottom: 50,
  },
  medicalCard: {
    color: "black",
    marginTop: 50,
    height: 0.5 * windowHeight,
    justifyContent: "center",
    flexDirection: "column",
    marginHorizontal: 0.1 * windowWidth,
  },
  card: {
    backgroundColor: "#fff",
    borderColor: "#91BCA0",
    elevation: 5,
    flexDirection: "row",
    justifyContent: "space-around",
    borderWidth: 1,
    width: 0.8 * windowWidth,
    alignItems: "center",
    marginVertical: 5,
    height: 50,
    borderRadius: 8,
  },

  password: {
    borderBottomWidth: 1,
    width: 115,
  },
  backButton: {
    backgroundColor: "#ACC0B3",
    width: 80,
    height: 40,
    borderWidth: 1,
    borderRadius: 10,
    alignItems: "center",
    justifyContent: "center",
    margin: 20,
  },
  messageContainer: {
    width: windowWidth,
    justifyContent: "center",
    alignItems: "center",
  },
  message: {
    textAlign: "center",
    color: "#000",
    fontWeight: "600",
  },
  success: {
    backgroundColor: "#ACC0B3",
    textAlignVertical: "center",
    width: 120,
    height: 30,
    borderRadius: 8,
  },
  error: {
    backgroundColor: "#B00020",
    textAlignVertical: "center",
    width: 120,
    height: 30,
    borderRadius: 8,
  },
  enlarge: {
    backgroundColor: "#fff",
    borderColor: "#91BCA0",
    flexDirection: "column",
    justifyContent: "space-around",
    borderWidth: 1,
    width: 0.8 * windowWidth,
    alignItems: "center",
    marginVertical: 5,
    height: 80,
    borderRadius: 8,
  },
  slant: {
    position: "absolute",
    height: windowHeight * 1.2,
    backgroundColor: "#344E41",
    width: windowWidth * 2,
    top: 0,
    right: 0,
    transform: [{ rotateY: "120deg" }, { rotateX: "45deg" }],
  },
  profileCardContainer: {
    width: windowWidth,
    height: 0.25 * windowHeight,
  },
  profileCard: {
    flex: 1,
    justifyContent: "center",
    flexDirection: "row",
    justifyContent: "space-between",
    width: 0.5 * windowWidth,
    margin: 20,
    paddingVertical: 20,
    paddingRight: 20,
    paddingLeft: 30,
    backgroundColor: "#DAD7CD",
    borderRadius: 12,
    elevation: 10,
  },
  name: {
    fontWeight: "bold",
    color: "#2E302F",
    fontSize: 24,
  },
  age: {
    fontWeight: "300",
  },
  EditInfoButton: {
    width: windowWidth * 0.9,
    height: 60,
    backgroundColor: "#307A55",
    position: "absolute",
    left: -1,
    bottom: -40,
    borderBottomRightRadius: 10,
    borderBottomLeftRadius: 10,
  },
  EditInfoText: {
    color: "#fff",
    fontWeight: "bold",
    fontSize: 30,
    textAlign: "center",
    textAlignVertical: "center",
    paddingTop: 10,
  },
  topSecMedicalCard: {
    flexDirection: "row",
    width: 0.8 * windowWidth,
    justifyContent: "space-between",
  },
  medicalRecordText: {
    fontWeight: "bold",
    color: "#307A55",
  },
  addMed: {
    fontWeight: "bold",
    color: "#F17754",
  },
  noRecordContainer: {
    flexDirection: "row",
    width: 0.8 * windowWidth,
    justifyContent: "space-between",
  },
  noMedical: {
    color: "black",
    height: 0.5 * windowHeight,
    justifyContent: "space-around",
    flexDirection: "column",
    marginHorizontal: 0.1 * windowWidth,
  },
  desc: {
    fontWeight: "bold",
    color: "#2E302F",
  },
  date: {
    fontWeight: "300",
  },
  dropDown: {
    width: 0.9 * windowWidth,
    marginHorizontal: 0.05 * windowWidth,
    borderWidth: 0.5,
    borderColor: "#91BCA0",
    borderRadius: 5,
    marginVertical: 15,
  },
});

export { infoStyles };
