# Generated by Django 4.0.5 on 2022-07-06 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Performance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.IntegerField()),
                ('status', models.CharField(max_length=40)),
                ('animal_Id', models.IntegerField()),
            ],
            options={
                'db_table': 'Performance_Profiles',
            },
        ),
    ]
