# Generated by Django 4.0.5 on 2022-07-25 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reminders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reminder',
            name='task_title',
            field=models.CharField(default=None, max_length=255),
            preserve_default=False,
        ),
    ]
