# Generated by Django 4.0.5 on 2022-07-08 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('farms', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='farm',
            old_name='farmer_Id',
            new_name='farmer',
        ),
        migrations.RenameField(
            model_name='farm',
            old_name='feeds_Id',
            new_name='feeds',
        ),
    ]
