# Generated by Django 4.0.5 on 2022-07-13 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farms', '0002_rename_farmer_id_farm_farmer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='farm',
            name='location',
            field=models.CharField(default=0, max_length=255),
        ),
    ]
