# Generated by Django 4.0.5 on 2022-07-15 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farms', '0003_farm_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='farm',
            name='farm_password',
            field=models.CharField(default=None, max_length=255),
        ),
        migrations.AddField(
            model_name='farm',
            name='milk_container_volume',
            field=models.IntegerField(default=None),
        ),
    ]
