# Generated by Django 4.0.5 on 2022-07-27 14:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_dob'),
        ('farms', '0005_remove_farm_farmer'),
    ]

    operations = [
        migrations.AddField(
            model_name='farm',
            name='farmer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='users.user'),
            preserve_default=False,
        ),
    ]
