# Generated by Django 4.0.5 on 2022-07-06 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('due_time', models.DateTimeField()),
                ('task_description', models.CharField(max_length=255)),
                ('animal_Id', models.IntegerField()),
            ],
            options={
                'db_table': 'Reminders',
            },
        ),
    ]
