# Generated by Django 4.0.5 on 2022-07-13 09:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('farms', '0003_farm_location'),
        ('animals', '0003_animal_qr_code_alter_animal_status'),
        ('reminders', '0002_reminder_farm_id_alter_reminder_animal_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reminder',
            name='animal_Id',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='animals.animal'),
        ),
        migrations.AlterField(
            model_name='reminder',
            name='farm_Id',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='farms.farm'),
        ),
    ]
