# Generated by Django 4.0.5 on 2022-07-13 09:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reminders', '0003_alter_reminder_animal_id_alter_reminder_farm_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reminder',
            old_name='animal_Id',
            new_name='animal',
        ),
        migrations.RenameField(
            model_name='reminder',
            old_name='farm_Id',
            new_name='farm',
        ),
    ]
