# Generated by Django 4.0.5 on 2022-07-13 09:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('farms', '0003_farm_location'),
        ('reminders', '0004_rename_animal_id_reminder_animal_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reminder',
            name='farm',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='farms.farm'),
        ),
    ]
