# Generated by Django 4.0.5 on 2022-07-27 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farms', '0006_farm_farmer'),
    ]

    operations = [
        migrations.AddField(
            model_name='farm',
            name='vet',
            field=models.IntegerField(default=None),
        ),
    ]
