# Generated by Django 4.0.5 on 2022-07-27 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farms', '0007_farm_vet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farm',
            name='vet',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
