# Generated by Django 4.0.5 on 2022-07-23 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='DOB',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
