# Generated by Django 4.0.5 on 2022-07-08 04:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_is_online'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='is_online',
            new_name='is_logged',
        ),
    ]
