# Generated by Django 4.0.5 on 2022-07-16 08:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('farms', '0002_remove_farm_recipe'),
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='farm',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='farms.farm'),
            preserve_default=False,
        ),
    ]
