# Generated by Django 4.0.5 on 2022-07-13 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feeds', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feed',
            old_name='Type',
            new_name='category',
        ),
        migrations.AddField(
            model_name='feed',
            name='acid_detergent_fibre_ADF',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='feed',
            name='crude_fibre_CF',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='feed',
            name='crude_protein_CP',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='feed',
            name='ether_extract_EE',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='feed',
            name='mineral_content_ASH',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='feed',
            name='neutral_detergent_fibre_NDF',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='feed',
            name='nitrogen_free_extract_NFE',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
