# Generated by Django 4.0.5 on 2022-07-14 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feeds', '0002_rename_type_feed_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='feed',
            name='Lignin',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='feed',
            name='Metabolizable_Energy_ME',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
