# Generated by Django 4.0.5 on 2022-07-14 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feeds', '0003_feed_lignin_feed_metabolizable_energy_me'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feed',
            name='Lignin',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='feed',
            name='Metabolizable_Energy_ME',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='feed',
            name='acid_detergent_fibre_ADF',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='feed',
            name='crude_fibre_CF',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='feed',
            name='crude_protein_CP',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='feed',
            name='ether_extract_EE',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='feed',
            name='mineral_content_ASH',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='feed',
            name='neutral_detergent_fibre_NDF',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='feed',
            name='nitrogen_free_extract_NFE',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
