# Generated by Django 4.0.5 on 2022-07-07 05:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('feeds', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Composition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('energy', models.DecimalField(decimal_places=2, max_digits=5)),
                ('protein_content', models.DecimalField(decimal_places=2, max_digits=5)),
                ('DM_content', models.DecimalField(decimal_places=2, max_digits=5)),
                ('CF_content', models.DecimalField(decimal_places=2, max_digits=5)),
                ('Minerals', models.CharField(max_length=255)),
                ('vitamins', models.CharField(max_length=255)),
                ('feeds_Id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='feeds.feed')),
            ],
            options={
                'db_table': 'Feed_Compositions',
            },
        ),
    ]
