# Generated by Django 4.0.5 on 2022-07-16 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Feed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('category', models.CharField(blank=True, max_length=50, null=True)),
                ('crude_protein_CP', models.CharField(blank=True, default=0, max_length=50, null=True)),
                ('ether_extract_EE', models.CharField(blank=True, default=0, max_length=50, null=True)),
                ('crude_fibre_CF', models.CharField(blank=True, default=0, max_length=50, null=True)),
                ('nitrogen_free_extract_NFE', models.CharField(blank=True, default=0, max_length=50, null=True)),
                ('neutral_detergent_fibre_NDF', models.CharField(blank=True, default=0, max_length=50, null=True)),
                ('acid_detergent_fibre_ADF', models.CharField(blank=True, default=0, max_length=50, null=True)),
                ('mineral_content_ASH', models.CharField(blank=True, default=0, max_length=50, null=True)),
                ('Lignin', models.CharField(blank=True, default=0, max_length=50, null=True)),
                ('Metabolizable_Energy_ME', models.CharField(blank=True, default=0, max_length=50, null=True)),
            ],
            options={
                'db_table': 'Feeds',
            },
        ),
    ]
