# Generated by Django 4.0.5 on 2022-07-16 06:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('farms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=55)),
                ('species', models.CharField(max_length=255)),
                ('breed', models.CharField(blank=True, max_length=255, null=True)),
                ('DOB', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(max_length=50)),
                ('status_updated_at', models.DateField(auto_now_add=True, null=True)),
                ('weight', models.IntegerField()),
                ('QR_code', models.TextField(blank=True, default=None, null=True)),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='farms.farm')),
            ],
            options={
                'db_table': 'Animals',
            },
        ),
    ]
