# Generated by Django 4.0.5 on 2022-07-13 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0003_animal_qr_code_alter_animal_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='status_updated_at',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='animal',
            name='weight',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
